spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/humanresources?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'
    username: root
    password: root53
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: '8088'
